# Generated by Django 4.2.5 on 2023-09-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1_day', '1 day'), ('3_days', '3 days'), ('1_week', '1 week')], max_length=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ert.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ert.reminder')),
            ],
        ),
    ]
